// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhmllrbocnungavzdswn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFobWxscmJvY251bmdhdnpkc3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMjIwNzIsImV4cCI6MjA3MDY5ODA3Mn0.dIpsJsERHTY3DA0t5OHWFOQySDc0_EiRMQWZaPOy1Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});